# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  #config.omnibus.chef_version = '12.10.24'
  #config.vm.network "private_network", ip: "192.168.50.4"
  #config.vm.provision "chef_solo", run_list: ["my_chef_cookbook"]

  puts "Running 1"
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "vm1"
    vm1.vm.network "private_network", ip: "192.168.50.4"
    puts "Running 2"
  end

  puts "Running 3"
  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "vm2"
    vm2.vm.network "private_network", ip: "192.168.50.5"
    puts "Running 4"
  end

  puts "Running 5"

end
