# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "vm1"
    vm1.vm.network "private_network", ip: "192.168.50.6"
    vm1.omnibus.chef_version = '12.10.24'
    vm1.vm.provision "chef_solo", run_list: ["java", "solr"]
  end

end
