# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  #config.omnibus.chef_version = '12.10.24'
  #config.vm.network "private_network", ip: "192.168.50.4"
  #config.vm.provision "chef_solo", run_list: ["my_chef_cookbook"]

  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "vm1"
    vm1.vm.provision :shell, path: "bootstrap_db.sh"
    vm1.vm.network "private_network", ip: "192.168.50.4"
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "vm2"
    vm2.vm.network "forwarded_port", guest: 80, host: 8080
    vm2.vm.provision :shell, inline: "apt-get -qq update; apt-get -y install mysql-client"
    vm2.vm.network "private_network", ip: "192.168.50.5"
  end

end
