# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Omnibus plugin is used to ensure that a desired version of Chef is installed.
  config.omnibus.chef_version = '12.10.24'

  # Installs chef-solo and runs the cookbook expected to be present at
  # cookbooks/<cookbook-name>/recipes/default.rb
  config.vm.provision "chef_solo", run_list: ["my_chef_cookbook"]
end
