# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.omnibus.chef_version = '12.10.24'

  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "vm1"

    config.vm.provision :chef_solo do |chef|
        chef.cookbooks_path = ['cookbooks', 'site-cookbooks']
        chef.run_list = [
          "recipe[oracle_java8::default]"
        ]
     end
  end
end
