# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.omnibus.chef_version = '12.10.24'
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.provision "chef_solo", run_list: ["my_chef_cookbook"]
end
